// backend/src/services/pdf.service.ts
import PDFDocument from 'pdfkit';
import type { Location, LocationInventory, TyreSizeCount } from '../types';
import type { TransferHistoryItem } from '../types/transfer.types';

interface PDFReportInput {
  location: Location;
  generatedAt: Date;
  generatedBy: string;
  summary: LocationInventory['summary'];
  bySize: TyreSizeCount[];
  transfersIn: TransferHistoryItem[];
  transfersOut: TransferHistoryItem[];
}

export class PDFService {
  static generateInventoryReport(data: PDFReportInput): PDFKit.PDFDocument {
    const doc = new PDFDocument({ margin: 50 });

    const { location, generatedAt, generatedBy, summary, bySize, transfersIn, transfersOut } = data;

    // Helper to draw a box
    const drawBox = (x: number, y: number, w: number, h: number, label: string, value: string, color: string = '#374151') => {
      doc.rect(x, y, w, h).stroke('#e5e7eb');
      doc.fontSize(9).fillColor('#6b7280').text(label, x + 5, y + 5, { width: w - 10 });
      doc.fontSize(16).fillColor(color).text(value, x + 5, y + 20, { width: w - 10, align: 'center' });
    };

    // Header
    doc.fontSize(24).fillColor('#111827').text('Tyre Inventory Report', 50, 50);
    doc.fontSize(10).fillColor('#6b7280');
    doc.text(`Location: ${location.name}`, 50, 80);
    doc.text(`Type: ${location.type}`, 50, 95);
    doc.text(`Address: ${location.address || 'N/A'}`, 50, 110);
    doc.text(`Generated: ${generatedAt.toLocaleString('en-IN')}`, 50, 125);
    doc.text(`Generated By: ${generatedBy}`, 50, 140);

    // Summary Boxes
    const boxY = 170;
    const boxW = 120;
    const boxH = 50;
    const gap = 10;

    drawBox(50, boxY, boxW, boxH, 'TOTAL TYRES', String(summary.totalTyres), '#111827');
    drawBox(50 + boxW + gap, boxY, boxW, boxH, 'WITH RIM', String(summary.totalWithRim), '#2563eb');
    drawBox(50 + (boxW + gap) * 2, boxY, boxW, boxH, 'WITHOUT RIM', String(summary.totalWithoutRim), '#6b7280');
    drawBox(50 + (boxW + gap) * 3, boxY, boxW, boxH, 'UNIQUE SIZES', String(bySize.length), '#059669');

    // Condition Breakdown
    let y = boxY + boxH + 30;
    doc.fontSize(14).fillColor('#111827').text('Condition Breakdown', 50, y);
    y += 25;

    const conditions = Object.entries(summary.byCondition);
    const condBoxW = 80;
    conditions.forEach(([condition, count], i) => {
      const x = 50 + (condBoxW + gap) * i;
      doc.rect(x, y, condBoxW, 40).stroke('#e5e7eb');
      doc.fontSize(14).fillColor('#111827').text(String(count), x, y + 5, { width: condBoxW, align: 'center' });
      doc.fontSize(8).fillColor('#6b7280').text(condition, x, y + 22, { width: condBoxW, align: 'center' });
    });

    // Size-wise Table
    y += 60;
    doc.fontSize(14).fillColor('#111827').text('Size-wise Inventory', 50, y);
    y += 25;

    // Table header
    const colWidths = [150, 120, 80, 80, 80];
    const colX = [50, 200, 320, 400, 480];
    const headers = ['Size', 'Brand / Pattern', 'Total', 'With Rim', 'Without'];

    doc.rect(50, y, 500, 20).fill('#f3f4f6');
    headers.forEach((h, i) => {
      doc.fontSize(9).fillColor('#374151').text(h, colX[i] + 5, y + 5, { width: colWidths[i] - 10 });
    });
    y += 20;

    // Table rows
    bySize.forEach((size, idx) => {
      if (y > 700) {
        doc.addPage();
        y = 50;
      }

      if (idx % 2 === 0) {
        doc.rect(50, y, 500, 20).fill('#fafafa');
      }

      doc.fontSize(9).fillColor('#111827').text(size.size, colX[0] + 5, y + 5, { width: colWidths[0] - 10 });
      doc.fontSize(9).fillColor('#6b7280').text(`${size.brand} ${size.pattern}`, colX[1] + 5, y + 5, { width: colWidths[1] - 10 });
      doc.fontSize(9).fillColor('#111827').text(String(size.total), colX[2] + 5, y + 5, { width: colWidths[2] - 10, align: 'right' });
      doc.fontSize(9).fillColor('#2563eb').text(String(size.withRim), colX[3] + 5, y + 5, { width: colWidths[3] - 10, align: 'right' });
      doc.fontSize(9).fillColor('#6b7280').text(String(size.withoutRim), colX[4] + 5, y + 5, { width: colWidths[4] - 10, align: 'right' });

      y += 20;
    });

    // Recent Transfers
    if (transfersIn.length > 0 || transfersOut.length > 0) {
      y += 20;
      if (y > 650) {
        doc.addPage();
        y = 50;
      }

      doc.fontSize(14).fillColor('#111827').text('Recent Transfers', 50, y);
      y += 25;

      // Incoming
      if (transfersIn.length > 0) {
        doc.fontSize(11).fillColor('#059669').text('Incoming', 50, y);
        y += 18;

        transfersIn.slice(0, 5).forEach(t => {
          doc.fontSize(9).fillColor('#374151').text(
            `${t.tyre.serialNumber} — ${t.tyre.brand} ${t.tyre.size} — From: ${t.fromLocation.name} — ${t.reason} — ${new Date(t.transferDate).toLocaleDateString('en-IN')}`,
            50, y, { width: 500 }
          );
          y += 14;
        });
      }

      // Outgoing
      if (transfersOut.length > 0) {
        y += 10;
        doc.fontSize(11).fillColor('#dc2626').text('Outgoing', 50, y);
        y += 18;

        transfersOut.slice(0, 5).forEach(t => {
          doc.fontSize(9).fillColor('#374151').text(
            `${t.tyre.serialNumber} — ${t.tyre.brand} ${t.tyre.size} — To: ${t.toLocation.name} — ${t.reason} — ${new Date(t.transferDate).toLocaleDateString('en-IN')}`,
            50, y, { width: 500 }
          );
          y += 14;
        });
      }
    }

    // Footer
    doc.fontSize(8).fillColor('#9ca3af').text(
      `Generated by Tyre Management System • ${generatedAt.toLocaleString('en-IN')}`,
      50, 750, { align: 'center', width: 500 }
    );

    doc.end();
    return doc;
  }
}
